<?php
return [
    'data:text/plain;base64'=>'txt',
    'data:application/msword;base64'=>'doc',
    'data:application/vnd.openxmlformats-officedocument.wordprocessingml.document;base64'=>'docx',
    'data:application/vnd.ms-excel;base64'=>'xlsx',
    'data:application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;base64'=>'pdf',
    'data:application/pdf;base64'=>'pptx',
    'data:application/vnd.openxmlformats-officedocument.presentationml.presentation;base64'=>'ppt',
    'data:application/vnd.ms-powerpoint;base64'=>'png',
    'data:image/png;base64'=>'png',
    'data:image/jpeg;base64'=>'jpeg',
    'data:image/jpg;base64'=>'jpg',
    'data:image/gif;base64'=>'gif',
    'data:image/svg+xml;base64'=>'svg',
    'data:image/x-icon;base64'=>'ico',
    'data:image/bmp;base64'=>'bmp',
    'data:application/octet-stream;base64'=>'bat',
];
